name: gradle

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: List generated JARs
        run: |
          echo "Contents of build/libs:"
          ls -l build/libs || echo "No JARs found!"

      - name: Upload each JAR as a separate artifact
        run: |
          for file in build/libs/*.jar; do
            echo "Uploading $file"
            artifact_name=$(basename "$file" .jar)
            gh run upload-artifact --name "$artifact_name" --path "$file"
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
