name: gradle

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 17
          distribution: zulu

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload build JARs
        uses: actions/upload-artifact@v4
        with:
          name: build-jars
          path: build/libs/*
